// Generated by Wrangler on Wed Apr 17 2024 12:40:41 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: "development";
	UPLOADTHING_SECRET: string;
	UPLOADTHING_APP_ID: string;
	ASTRO_STUDIO_APP_TOKEN: string;
}
